name: test actions

on: pull

job: 

  job1:
    runs-on: ubuntu-latest
    -run: date

  job2:
  runs-on: windows-latest
    -run: date

  job3:
  runs-on: macos-latest
    -run: date

  job4:
    needs: [job1,job2,job3]
    runs-on: windows-latest
    -run: date
  
